events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    # events_list views
    path('', views.events_list, name='events_list'),
    path('search', views.search_result, name='search_result'),
    path('<int:event_id>', views.event_detail, name='event_detail'),
    path('add', views.add_event, name='add_event'),
    path('feed', views.feed_page, name='feed_page'),
    path('<int:event_id>/edit', views.edit_event, name='edit_event'),
    path('event/interation', views.event_button_interaction, name='event_interaction'),
    path('event/register', views.event_register_interaction, name='event_register'),
    path('sort/<str:option>', views.sort_list, name='sort_events'),
    path('delete', views.delete_event, name='delete_event'),
]

great_fall_events/urls.py
from django.contrib import admin
from django.urls import path, include

from events import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace="events")),
    path('users/', include('users.urls', namespace="users")),
    path('', views.home_page, name="index"),
    path('feed/interation', views.user_info_interaction, name='user_interaction'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/change', views.change_user_role, name='change_role'),
    path('<str:username>/profile', views.profile, name='profile'),
    path('<str:username>/profile/edit', views.edit_user, name='edit_profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('post-comment', views.post_comment, name='post_comment'),
    path('<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('delete', views.delete_comment, name='delete_comment'),
]

events/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=200)
    image = models.CharField(max_length=200, default="img/events/default_event.jpg")
    location = models.CharField(max_length=200)
    date = models.CharField(default="11/10/2021", max_length=30)
    time = models.CharField(default="11:00 AM", max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    organizer = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attendees = models.IntegerField(default=0)
    like_number = models.IntegerField(default=0)
    share_number = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[self.id])


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


class Account(models.Model):
    title = models.CharField(max_length=30)
    gender = models.CharField(max_length=20)
    age = models.IntegerField(default=20)
    group = models.CharField(max_length=50)
    intro = models.CharField(max_length=200)
    image = models.CharField(max_length=200, default="img/profile/anonymous-user.png")

# regular_user = {"username": "alice", "password": "hokie"}
# admin_user = {"username": "admin", "password": "admin"}

events/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect

from actions.models import Action
from .models import Event, Account, Comment


# Create your views here.
def events_list(request):
    events = Event.objects.all().order_by('date').filter(is_deleted=False)
    return render(request,
                  "events/posts/list.html",
                  {"events": events}
                  )


def sort_list(request, option):
    events = Event.objects.all().order_by(option).filter(is_deleted=False)
    return render(request,
                  "events/posts/list.html",
                  {"events": events}
                  )


def event_detail(request, event_id):
    event = Event.objects.get(pk=event_id)
    all_comments = Comment.objects.all().order_by('-time')
    comments = []
    for comment in all_comments:
        if comment.event_id == event.id:
            comments.append(comment)
    return render(request,
                  'events/posts/item_detail.html',
                  {'event': event, 'comments': comments}
                  )


def home_page(request):
    event = Event.objects.get(pk=1)
    actions = Action.objects.all().order_by('-created')[:8]
    return render(request,
                  "events/homes/home_page.html",
                  {'event': event, 'actions': actions}
                  )


def search_result(request):
    return render(request,
                  "events/homes/search_result.html"
                  )


def feed_page(request):
    users = Account.objects.all()
    return render(request,
                  "events/posts/feeds-additional_page.html",
                  {"users": users}
                  )


def add_event(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        location = request.POST.get('location')
        date = request.POST.get('date')
        time = request.POST.get('time')
        description = request.POST.get('description')
        user = User.objects.get(username=request.session.get('username'))
        new_event = Event(
            title=title,
            location=location,
            date=date,
            time=time,
            description=description,
            organizer=request.session.get('username'),
            user=user

        )
        new_event.save()
        # log the action
        action = Action(
            user=user,
            verb="created the new event",
            target=new_event
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully added a new event: %s" % new_event.title)
        return redirect('events:event_detail', new_event.id)
    else:
        return render(request, 'events/posts/add_new_event.html')


def edit_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        if event.title != title:
            title_change_action = Action(
                user=event.user,
                verb="edited the event title",
                target=event
            )
            title_change_action.save()

        description = request.POST.get('description')
        if event.description != description:
            description_change_action = Action(
                user=event.user,
                verb="edited the event description",
                target=event
            )
            description_change_action.save()

        event.location = request.POST.get('location')
        event.date = request.POST.get('date')
        event.time = request.POST.get('time')
        event.title = title
        event.description = description
        event.save()
        messages.add_message(request, messages.INFO, "You successfully edit the event: %s" % event.title)
        return redirect('events:event_detail', event_id)
    else:
        return render(request,
                      "events/posts/add_new_event.html", {'event': event})


def event_button_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        event_id = request.POST.get('event_id')
        button_name = request.POST.get('button_name')
        try:
            event = Event.objects.get(pk=event_id)
            if button_name == 'shareButton':
                event.share_number = event.share_number + 1
            else:
                event.like_number = event.like_number + 1
            event.save()
            return JsonResponse(
                {'success': 'success', 'button_name': button_name, 'like_number': event.like_number,
                 'share_number': event.share_number},
                status=200)
        except Event.DoesNotExist:
            return JsonResponse({'error': 'No Event found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def delete_event(request):
    if request.method == 'POST':
        event_id = request.POST.get('event_id')
        event = Event.objects.get(pk=event_id)
        event.is_deleted = True
        event.save()
        delete_event_action = Action(
            user=event.user,
            verb="delete the event",
            target=event
        )
        delete_event_action.save()
        messages.add_message(request, messages.WARNING, "You successfully delete the event: %s" % event.title)
        redirect('events:events_list')
    return redirect('events:events_list')


def user_info_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        user_id = request.POST.get('user_id')
        print(user_id)
        try:
            user = Account.objects.get(pk=user_id)
            return JsonResponse(
                {'success': 'success', 'name': user.title, 'age': user.age,
                 'gender': user.gender, 'group': user.group, 'intro': user.intro},
                status=200)
        except Account.DoesNotExist:
            return JsonResponse({'error': 'No User profile found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def event_register_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        event_id = request.POST.get('event_id')
        button_text = request.POST.get('button_text')
        try:
            event = Event.objects.get(pk=event_id)
            if button_text == "Register":
                event.attendees += 1
                button_name = "Unregister"
            else:
                event.attendees -= 1
                button_name = "Register"
            event.save()
            return JsonResponse(
                {'success': 'success', 'attendees': event.attendees, 'button_name': button_name},
                status=200)
        except Event.DoesNotExist:
            return JsonResponse({'error': 'No Event found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)

templates/events/posts/add_new_event.html
{% extends "events/base.html" %}
{% block page-title %}Add a new event{% endblock %}
{% load static %}
{% block content %}
    <link type="text/css" href="{% static "css/add_new_event.css" %}" rel="stylesheet">
    {% if request.session.username %}
        <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>jQuery UI Datepicker - Default functionality</title>
            <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
            <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
            <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
            <script>
                $(function () {
                    $("#datepicker").datepicker();
                });
            </script>
        </head>
        <body>
        {% if event %}
            {# when event.id is passing, display the edit event view#}
            <form class="createEvent" name="edit-event" method="POST">
                {% csrf_token %}
                <p class="eventTitle">
                    <strong>Title:</strong>
                    <input type="text" id="eventTitleInput" name="title" value="{{ event.title }}" required>
                </p>
                <p class="eventLocation">
                    <strong>Location:</strong>
                    <input type="text" id="eventLocationInput" name="location" value="{{ event.location }}" required>
                </p>
                <p><strong>Date:</strong> <input type="text" name="date" id="datepicker" value="{{ event.date }}" required></p>
                <p><strong>Time:</strong> <input type="text" name="time" value="{{ event.time }}" required>
                    <small id="format">(Following
                    Format: 10:00 AM)</small></p>
                <div class="eventDescription">
                    <strong>Event Description:</strong>
                </div>
                <textarea id="eventDescriptionInput" name="description">{{ event.description }}</textarea>
                <input id="submitButton" type="submit" value="submit">
            </form>
        {% else %}
            {# when event.id is not passing, display the add event view#}
            <form class="createEvent" name="create-event"
                  action="{% url "events:add_event" %}" method="POST">
                {% csrf_token %}
                <p class="eventTitle">
                    <strong>Title:</strong>
                    <input type="text" id="eventTitleInput" name="title" required>
                </p>
                <p class="eventLocation">
                    <strong>Location:</strong>
                    <input type="text" id="eventLocationInput" name="location" required>
                </p>
                <p><strong>Date:</strong> <input type="text" name="date" id="datepicker"></p>
                <p><strong>Time:</strong> <input type="text" name="time"> <small id="format">(Following Format: 10:00
                    AM)</small></p>
                <div class="eventDescription">
                    <strong>Event Description:</strong>
                </div>
                <textarea id="eventDescriptionInput" name="description"></textarea>
                <input id="changeRole" type="submit" value="submit">
            </form>
        {% endif %}

        {#if user is not loggined, the edit/add view wont be displayed#}
    {% else %}
        <h3> Log in to create an Event!</h3>
    {% endif %}
    </body>
{% endblock %}

</html>

templates/events/posts/feeds-additional_page.html
{% extends "events/base.html" %}
{% block page-title %}Feeds of GreatFall networking{% endblock %}
{% load static %}

{% block content %}
    <link href="{% static "css/feed_page.css" %}" rel="stylesheet">
    <section id="postsArea">
        <div class="postBlock">
            <div class="userImage" data-user-id="1" data-ajax-url="{% url "user_interaction" %}">
                <img class="heartsQueen" alt="knave-of-hearts"
                     src="{% static "img/site/knave-of-hearts.png" %}">
                <p>Hearts Queen</p>
            </div>
            <div class="userInfo">
            </div>
            <h4><a href="#"> Where is the best spot for picnic in the
                Virginia side? </a></h4>
            <div class="postInfo">
                <div>view 22</div>
                <div>replies 2</div>
            </div>
        </div>

        <div class="postBlock">
            <div class="userImage" data-user-id="2" data-ajax-url="{% url "user_interaction" %}" >
                <img alt="cheshire-cat"
                     src="{% static "img/site/cheshire-cat.jpg" %}">
                <p>Cheshire Cat</p>
            </div>
            <div class="userInfo">
            </div>
            <h4><a href="#"> A lovely view from the Maryland side </a></h4>
            <div class="postInfo">
                <div>view 122</div>
                <div>replies 34</div>
            </div>
        </div>

        <div class="postBlock">
            <div class="userImage" data-user-id="3" data-ajax-url="{% url "user_interaction" %}">
                <img alt="anonymous-user"
                     src="{% static "img/site/anonymous-user.png" %}">
                <p>Anonymous User</p>
            </div>
            <div class="userInfo">
            </div>
            <h4><a href="#"> Which one is the easiest trail in the
                Virginia side? </a></h4>
            <div class="postInfo">
                <div>view 22</div>
                <div>replies 2</div>
            </div>
        </div>

    </section>
    {#    <!--  user editor area -->#}
    {#    <section id="textEditorArea">#}
    {#        <div class="yourImage">#}
    {#            <a href="#">#}
    {#                <img alt="yourImage"#}
    {#                     src="{% static "img/site/alice.png" %}">#}
    {#            </a>#}
    {#            <p>Alice</p>#}
    {#        </div>#}
    {#        <textarea cols="100" id="textEditor" rows="12">#}
    {#                Write your own post...#}
    {#            </textarea>#}
    {#        <button>#}
    {#            Post#}
    {#        </button>#}
    {#    </section>#}
{% endblock %}

templates/events/posts/item_detail.html
{% extends "events/base.html" %}
{% block page-title %}Event Detail{% endblock %}
{% load static %}
{% block detailContent %}
    <link href="{% static "css/item_with_details.css" %}" rel="stylesheet">
    <script src="{% static "js/profile.js" %}"></script>
    <section id="mainContent">
        <section id="eventBlock">
            <div id="eventPart1">
                <div id="eventImageInEventPage">
                    <a href="{%  url 'events:event_detail' event.id %}">
                        <img alt="bird watchers"
                             src="{% static event.image %}">
                    </a>
                </div>
                <div id="eventInfoAndButton">
                    <ul class="eventInfo">
                        <li class="eventTitle">{{ event.title }}</li>
                        <li class="eventLocation">{{ event.location }}</li>
                        <li class="eventTime">{{ event.date }}</li>
                        <li class="eventTime">{{ event.time }}</li>
                        <li class="organizer"><a href={% url 'users:profile' event.user.username %}> Organized
                            by: {{ event.user.username }}</a></li>
                        <li class="dateCreated">Date Posted: {{ event.created_date }}</li>
                        <li class="attendees">
                            <span class="attendeesNumber">{{ event.attendees }}</span>
                            &nbsp;attendees
                            <span class="likeNumber">{{ event.like_number }}</span>
                            &nbsp;likes
                            <span class="shareNumber">{{ event.share_number }}</span>
                            &nbsp;shares
                        <li>
                    </ul>
                    {% if request.session.username %}
                        <button class="register" data-ajax-url="{% url "events:event_register" %}">Register</button>
                        {% if request.session.role == 'admin' or request.session.username == event.user.username%}
                            <button><a href="{% url "events:edit_event" event.id %}">Edit</a></button>
                            <form id="delete" name="delete-event" action="{% url "events:delete_event" %}"
                                  method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="event_id" value="{{ event.id }}">
                                <button class="delete">Delete</button>
                            </form>
                        {% endif %}
                        <div class="eventButton" data-event-id="{{ event.id }}"
                             data-ajax-url="{% url "events:event_interaction" %}">
                            <img class="shareButton" alt="share-icon"
                                 src="{% static "img/site/share-icon.png" %}">
                            <img class="likeButton" alt="like-icon"
                                 src="{% static "img/site/like-icon.png" %}">
                        </div>
                    {% endif %}

                </div>
            </div>
            </div>
            <div id="eventDescription">
                <h5>About Bird Watchers</h5>
                <div id="description">
                    {{ event.description }}
                </div>
            </div>
        </section>

        <section id="attendees">
            <h5>Attendees</h5>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="The Mad Hatter"
                         src="{% static "img/profile/the-mad-hatter.jpeg" %}">
                </a>
                <p>The Mad Hatter</p>
            </div>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="Caterpillar"
                         src="{% static "img/profile/caterpillar.png" %}">
                </a>
                <p>Caterpillar</p>
            </div>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="White Rabbit"
                         src="{% static "img/profile/white-rabbit.jpg" %}">
                </a>
                <p>White Rabbit</p>
            </div>

            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="dodo"
                         src="{% static "img/profile/dodo.jpg" %}">
                </a>
                <p>Dodo</p>
            </div>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="Mock Turtle"
                         src="{% static "img/profile/mock-turtle.jpg" %}">
                </a>
                <p>Mock Turtle</p>
            </div>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="Cheshire Cat"
                         src="{% static "img/profile/cheshire-cat.jpg" %}">
                </a>
                <p>Cheshire Cat</p>
            </div>
            <div class="attendeeBlock">
                <a class="attendImage" href="#">
                    <img alt="MarchHare"
                         src="{% static "img/profile/march-hare.png" %}">
                </a>
                <p>MarchHare</p>
            </div>
        </section>
    </section>
{% endblock %}

{% block detailContentRecentPhotos %}
    <section id="recentPhotos">
        <h5>Recent Photos From this Event</h5>
        <div id="recentPhotosBlock">
            <a class="feedImage" href="#">
                <img alt="feed1"
                     src="{% static "img/feed/season-feed1.png" %}">
            </a>
            <a class="feedImage" href="#">
                <img alt="feed2"
                     src="{% static "img/feed/season-feed2.jpg" %}">
            </a>
            <a class="feedImage" href="#">
                <img alt="feed3"
                     src="{% static "img/feed/season-feed3.jpg" %}">
            </a>
        </div>
        <h5>Comments of this Event</h5>
        <div id = "newComment"></div>
        {% for comment in comments %}
            <div class="commentBlock">
                <div class="commentContent">{{ comment.content }} </div>
                <div class="commentInfo">
                    <div class="commentName">Post by:
                        <a href={% url 'users:profile' comment.author.username %}>{{ comment.author.username }}</a>
                    </div>
                    <div class="commentTime">{{ comment.time }}</div>

                {#edit and delete function, users can delete/edit comments posted by them, admin can do it in any comments#}
                {% if request.session.username  == comment.author.username or request.session.role == "admin" %}
                    <div class = "commentButtons">
                   <button class = "edit"><a href="{% url "users:edit_comment" comment.id %}">Edit</a></button>
                    <form name="delete-comment" data-ajax-url="{% url 'users:delete_comment' %}"
                          data-comment-id="{{ comment.id }}">
                        {% csrf_token %}
                        <input type = "button" class="deleteComment" value = "delete">
                    </form>
                    </div>
                {% endif %}
                </div>
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
            </div>

        {% empty %}
            <p class="noComment">No Comments yet. Try to add a new one yourself!</p>
        {% endfor %}
        {% if request.session.username %}
            {% if comment %}
{#                 when comment.id is passing, display the edit comment view#}
               <h5 class = "titleTextArea">Edit your comment for this Event</h5>
                <form id="postComment" data-ajax-url="{% url 'users:edit_comment' comment.id %}"
                      data-user-name="{{ request.session.username }}"
                      data-event-id="{{ event.id }}"
                data-operation-type = "edit">
                    {% csrf_token %}
                    <textarea cols="40" class="textEditor" rows="3" name="comment-text"
                              placeholder="Post a comment for this event..">{{ comment.content }}</textarea>
                    <input id="submitCommentButton" type="button" value="post">
                </form>
            {% else %}
                <!--  post comment area -->
                <h5 class = "titleTextArea">Post a Comment as <a href={% url 'users:profile' request.session.username %}></a> for this Event
                </h5>
                <form id="postComment" data-ajax-url="{% url 'users:post_comment' %}"
                      data-user-name="{{ request.session.username }}"
                      data-event-id="{{ event.id }}"
                data-operation-type = "add">
                    {% csrf_token %}
                    <textarea cols="40" class="textEditor" rows="3" name="comment-text"
                              placeholder="Post a comment for this event.."></textarea>
                    <input id="submitCommentButton" type="button" value="post">
                </form>
            {% endif %}
        {% else %}
            <p class="noComment">Login in to post a comment!</p>
        {% endif %}
    </section>
{% endblock %}

templates/events/posts/list.html
{% extends "events/base.html" %}
{% block page-title %}List of Events {% endblock %}
{% load static %}

{% block side-tabs %}
    <link href="{% static "css/listing_item_page.css" %}" rel="stylesheet">
        <ul id="side-tabs">
        <li><strong>Sorted By:</strong></li>
        <li><a href="{% url "events:sort_events" "-date" %}">Date</a></li>
        <li><a href="{% url "events:sort_events" "-attendees" %}">Number of Attendees</a></li>
        <li><a href="{% url "events:sort_events" "-like_number" %}">Number of Likes</a></li>
        <li><a href="{% url "events:sort_events" "-share_number" %}">Number of Shares</a></li>
    </ul>
{% endblock %}
{% block contentForList %}
    <link href="{% static "css/listing_item_page.css" %}" rel="stylesheet">
    <ul id="eventBoxes">
        {% for event in events %}
            <li class="eventBlock">
                <div class="eventImage">
                    <a href="{% url "events:event_detail" event.id %}">
                        <img alt="event image"
                             src="{% static event.image %}">
                    </a>
                </div>
                <ul class="eventInfo">
                    <li class="eventTitle">
                        <a href="{% url "events:event_detail" event.id %}">{{ event.title }}</a>
                    </li>
                    <li class="eventLocation">{{ event.location }}</li>
                    <li class="eventTime">{{ event.date }}</li>
                    <li class="eventTime">{{ event.time }}</li>
                    <li class="attendees">
                        <span class="attendeesNumber">{{ event.attendees }}</span>
                        &nbsp;attendees
                        <span class="likeNumber">{{ event.like_number }}</span>
                        &nbsp;likes
                        <span class="shareNumber">{{ event.share_number }}</span>
                        &nbsp;shares
                    </li>
                </ul>
                {% if request.session.username %}
                    <div class="eventButton" data-event-id="{{ event.id }}"
                         data-ajax-url="{% url "events:event_interaction" %}">
                        <img class="shareButton" alt="share-icon"
                             src="{% static "img/site/share-icon.png" %}">
                        <img class="likeButton" alt="like-icon"
                             src="{% static "img/site/like-icon.png" %}">
                    </div>
                {% endif %}
            </li>
             {% empty %}
            <H2>No events available. Try to add a new one yourself!</H2>
        {% endfor %}
    </ul>
{% endblock %}