great_fall_events/urls.py
from django.contrib import admin
from django.urls import path, include

from events import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace="events")),
    path('users/', include('users.urls', namespace="users")),
    path('', views.home_page, name="index"),
    path('feed/interation', views.user_info_interaction, name='user_interaction'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/change', views.change_user_role, name='change_role'),
    path('<str:username>/profile', views.profile, name='profile'),
    path('<str:username>/profile/edit', views.edit_user, name='edit_profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('post-comment', views.post_comment, name='post_comment'),
    path('<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('delete', views.delete_comment, name='delete_comment'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
from django.urls import reverse


class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)
    gender = models.CharField(default="not disclosed", max_length=50)

    def get_absolute_url(self):
        return reverse('users:profile', args=[self.user.username])


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate
import datetime
# Create your views here.
from actions.models import Action
from events.models import Event, Comment


def profile(request, username):
    user1 = get_object_or_404(User, username=username)
    user_actions = Action.objects.all().filter(user_id=user1.id).order_by('-created')[:5]
    return render(request, "users/user/profile.html",
                  {"user": user1, "actions": user_actions})


def change_user_role(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        user_id = request.POST.get('user_id')
        user_role = request.POST.get('user_role')
        operator_account = request.POST.get('operator_account')
        operator = User.objects.get(username=operator_account)
        try:
            user = User.objects.get(pk=user_id)
            user.details.role = user_role
            user.details.save()
            user.save()
            change_role_action = Action(
                user=operator,
                verb="changed the role",
                target=user
            )
            change_role_action.save()
            return JsonResponse(
                {'success': 'success', 'user_role': user_role},
                status=200)
        except User.DoesNotExist:
            return JsonResponse({'error': 'No User found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.WARNING,
                                 "This username has been taken.")
            return redirect('users:register')
        if User.objects.filter(email=email).exists():
            messages.add_message(request, messages.WARNING,
                                 "This email has been used.")
            return redirect('users:register')
        user = User.objects.create_user(username, email, password)
        user.first_name = request.POST.get('firstname')
        user.last_name = request.POST.get('lastname')
        user.save()
        request.session['username'] = username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS, "You successfully register a new account: %s" % user.username)
        return redirect('index')
    else:
        return render(request, "users/user/register.html")


def login_user(request):
    username = request.POST.get("username")
    password = request.POST.get("pw")
    user = authenticate(username=username, password=password)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS,
                             "You have logged in successfully.")
    else:
        messages.add_message(request, messages.ERROR,
                             "Invalid username or password.")
    return redirect('index')


def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('index')


def edit_user(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        user.first_name = request.POST.get('firstname')
        user.last_name = request.POST.get('lastname')
        user.email = request.POST.get('email')
        user.set_password(request.POST.get('password'))
        user.details.gender = request.POST.get('gender')
        user.save()
        messages.add_message(request, messages.INFO, "You successfully edit user account: %s" % user.username)

        return redirect('users:profile', username)
    else:
        return render(request, "users/user/register.html", {'user_account': user})


def post_comment(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        text = request.POST.get('text')
        username = request.POST.get('username')
        event_id = request.POST.get('event_id')
        try:
            event = Event.objects.get(pk=event_id)
            user = User.objects.get(username=username)
            new_comment = Comment(
                content=text,
                author=user,
                event=event
            )
            new_comment.save()
            messages.add_message(request, messages.SUCCESS, "You successfully posted a new comment.")
            return JsonResponse(
                {'success': 'success', 'content': new_comment.content, 'username': new_comment.author.username,
                 'time': new_comment.time},
                status=200)
        except User.DoesNotExist:
            return JsonResponse({'error': 'No User or Event found with that id.'}, status=200)

    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def edit_comment(request, comment_id):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        try:
            comment = Comment.objects.get(pk=comment_id)
            comment.content = request.POST.get('text')
            comment.time = datetime.datetime.now()
            comment.save()
            messages.add_message(request, messages.INFO, "You successfully edit the comment")
            return JsonResponse(
                {'success': 'success', 'comment_id': comment.id, 'content': comment.content,
                 'username': comment.author.username,
                 'time': comment.time},
                status=200)
        except Comment.DoesNotExist:
            return JsonResponse({'error': 'No Comment found with that id.'}, status=200)
    else:
        # return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)
        comment = Comment.objects.get(pk=comment_id)
        event = comment.event
        comments = fetch_comment_for_an_event(event.id)
        return render(request,
                      "events/posts/item_detail.html", {'event': event, 'comments': comments, 'comment': comment})


def delete_comment(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        comment_id = request.POST.get('comment_id')
        try:
            comment = Comment.objects.get(pk=comment_id)
            comment.delete()
            return JsonResponse(
                {'success': 'success', 'comment_id': comment_id},
                status=200)
        except Comment.DoesNotExist:
            return JsonResponse({'error': 'No Comment found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def fetch_comment_for_an_event(event_id):
    all_comments = Comment.objects.all().order_by('-time')
    comments = []
    for comment in all_comments:
        if comment.event_id == event_id:
            comments.append(comment)
    return comments

templates/users/user/profile.html
{% extends "events/base.html" %}
{% block page-title %}Profile Page for {{ user.name }}{% endblock %}
{% load static %}
{% block content %}
    <script src="{% static "js/profile.js" %}"></script>
    <link href="{% static "css/profile_page.css" %}" rel="stylesheet">
    <h2>Profile of {{ user.username }}
        {% if request.session.username == user.username or request.session.role == "admin" %}
            <button id="editButtonProfile"><a href="{% url "users:edit_profile" user.username %}">Edit This Profile</a>
            </button>
        {% endif %}</h2>
    <ul id="userInfoBlock">
        <li class="userData">
            <span class="userInfoTitle">Username:</span>
            <span>{{ user.username }}</span>
        </li>
        <li class="userData"><span class="userInfoTitle">First Name:</span>
            {% if user.first_name %}
                <span> {{ user.first_name }}</span>
            {% else %}
                <span> Not Disclosed</span>
            {% endif %}
        </li>
        <li class="userData"><span class="userInfoTitle">Last Name:</span>
            {% if user.last_name %}
                <span> {{ user.last_name }}</span>
            {% else %}
                <span> Not Disclosed</span>
            {% endif %}
        </li>
        <li class="userData">
            <span class="userInfoTitle">Email Address:</span> <span>{{ user.email }}</span>
        </li>
        <li class="userData"><span class="userInfoTitle">Gender:</span> <span>{{ user.details.gender }}</span></li>
        <li class="userData"><span class="userInfoTitle">Role: </span><span
                id="new-role"> {{ user.details.role }}</span></li>
    </ul>

    <h3>Recent Activities From this User</h3>
    <section id="recentActivities">
        {% include "actions/action/activity.html" %}
    </section>
    {% if request.session.role == "admin" %}
        <h4>For Admin Only</h4>
        <div id="roleChange">
        <label for="role-options">Do you want change this user's role</label>

            <select id="role-options" name="role-options"
                    data-operator-name="{{ request.session.username }}" data-ajax-url="{% url "users:change_role" %}"
                    data-user-id="{{ user.id }}">
                <option value="admin">Admin</option>
                <option value="regular">Regular</option>
                <option value="unregister">Unregister</option>
            </select>
            <button id="submitButton" type="submit" value="submit">Submit</button>
        </div>
    {% endif %}

{% endblock %}

templates/users/user/register.html
{% extends "events/base.html" %}
{% block page-title %}Register a user{% endblock %}
{% load static %}
{% block content %}
        <link type="text/css" href="{% static "css/register_page.css" %}" rel="stylesheet">
    {# when user is passing, display the edit profile view#}
    {% if user_account %}
        <h2>Edit Profile Information</h2>
        <form class="registerUser" name="edit-user" method="POST">
            {% csrf_token %}
            <p> * = required.</p>
            <p class="userName">
                <strong>Username *</strong>
                <input type="text" id="userNameInput" name="username" value="{{ user_account.username }}" disabled>
            </p>
            <p class="firstName">
                <strong>First Name *</strong>
                <input type="text" id="userNameInput" name="firstname" value="{{ user_account.first_name }}" required>
            </p>
            <p class="lastName">
                <strong>Last Name *</strong>
                <input type="text" id="userNameInput" name="lastname" value="{{ user_account.last_name }}" required>
            </p>
            <p class="userEmail">
                <strong>Email Address *</strong>
                <input type="email" id="userEmailInput" name="email" value="{{ user_account.email }}" required>
            </p>
            <p class="userPassword">
                <strong>Password</strong>
                <input type="password" id="userPasswordInput" value="{{ user_account.password }}" name="password" required>
            </p>
              <label class = "userGender"> Gender</label>
                <label for="male">Male</label>
                <input type="radio" id="male" name="gender" value="male"/>
                <label for="female">Female</label>
                <input type="radio" id="female" name="gender" value="female"/>
                <label for="other">Others</label>
                <input type="radio" id="others" name="gender" value="others"/>
                <label for="notDisclose">Not Disclose</label>
                <input type="radio" id="notDisclose" name="gender" value="not disclosed" checked/>
            <input id="submitButton" type="submit" value="submit">
        </form>
    {% else %}
        {# when user is not passing, display the add profile view#}
        <h2>Register User Account</h2>
        <form class="registerUser" name="register user"
              action="{% url "users:register" %}" method="POST">
            {% csrf_token %}
            <p> * = required.</p>
            <p class="userName">
                <strong>Username *</strong>
                <input type="text" id="userNameInput" name="username" required>
            </p>
            <p class="firstName">
                <strong>First Name *</strong>
                <input type="text" id="userNameInput" name="firstname" value="" required>
            </p>
            <p class="lastName">
                <strong>Last Name *</strong>
                <input type="text" id="userNameInput" name="lastname" value="" required>
            </p>
            <p class="userEmail">
                <strong>Email Address *</strong>
                <input type="email" id="userEmailInput" name="email" required>
            </p>
            <p class="userPassword">
                <strong>Password *</strong>
                <input type="password" id="userPasswordInput" name="password" required>
            </p>
             <label class = "userGender"> Gender</label>
            <label for="male">Male</label>
            <input type="radio" id="male" name="gender"/>
            <label for="female">Female</label>
            <input type="radio" id="female" name="gender"/>
            <label for="other">Others</label>
            <input type="radio" id="others" name="gender"/>
            <label for="notDisclose">Not Disclose</label>
            <input type="radio" id="notDisclose" name="gender"/>

          <input id="submitButton" type="submit" value="submit">
        </form>
    {% endif %}
{% endblock %}