events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    # events_list views
    path('', views.events_list, name='events_list'),
    path('search', views.search_result, name='search_result'),
    path('<int:event_id>', views.event_detail, name='event_detail'),
    path('add', views.add_event, name='add_event'),
    path('feed', views.feed_page, name='feed_page'),
    path('<int:event_id>/edit', views.edit_event, name='edit_event'),
    path('event/interation', views.event_button_interaction, name='event_interaction'),
    path('event/register', views.event_register_interaction, name='event_register'),
    path('sort/<str:option>', views.sort_list, name='sort_events'),
    path('delete', views.delete_event, name='delete_event'),
]

great_fall_events/urls.py
from django.contrib import admin
from django.urls import path, include

from events import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace="events")),
    path('users/', include('users.urls', namespace="users")),
    path('', views.home_page, name="index"),
    path('feed/interation', views.user_info_interaction, name='user_interaction'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('profile/change', views.change_user_role, name='change_role'),
    path('<str:username>/profile', views.profile, name='profile'),
    path('<str:username>/profile/edit', views.edit_user, name='edit_profile'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('post-comment', views.post_comment, name='post_comment'),
    path('<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('delete', views.delete_comment, name='delete_comment'),
]

events/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=200)
    image = models.CharField(max_length=200, default="img/events/default_event.jpg")
    location = models.CharField(max_length=200)
    date = models.CharField(default="11/10/2021", max_length=30)
    time = models.CharField(default="11:00 AM", max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    organizer = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attendees = models.IntegerField(default=0)
    like_number = models.IntegerField(default=0)
    share_number = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[self.id])


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


class Account(models.Model):
    title = models.CharField(max_length=30)
    gender = models.CharField(max_length=20)
    age = models.IntegerField(default=20)
    group = models.CharField(max_length=50)
    intro = models.CharField(max_length=200)
    image = models.CharField(max_length=200, default="img/profile/anonymous-user.png")

# regular_user = {"username": "alice", "password": "hokie"}
# admin_user = {"username": "admin", "password": "admin"}

events/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect

from actions.models import Action
from .models import Event, Account, Comment


# Create your views here.
def events_list(request):
    events = Event.objects.all().order_by('date').filter(is_deleted=False)
    return render(request,
                  "events/posts/list.html",
                  {"events": events}
                  )


def sort_list(request, option):
    events = Event.objects.all().order_by(option).filter(is_deleted=False)
    return render(request,
                  "events/posts/list.html",
                  {"events": events}
                  )


def event_detail(request, event_id):
    event = Event.objects.get(pk=event_id)
    all_comments = Comment.objects.all().order_by('-time')
    comments = []
    for comment in all_comments:
        if comment.event_id == event.id:
            comments.append(comment)
    return render(request,
                  'events/posts/item_detail.html',
                  {'event': event, 'comments': comments}
                  )


def home_page(request):
    event = Event.objects.get(pk=1)
    actions = Action.objects.all().order_by('-created')[:8]
    return render(request,
                  "events/homes/home_page.html",
                  {'event': event, 'actions': actions}
                  )


def search_result(request):
    return render(request,
                  "events/homes/search_result.html"
                  )


def feed_page(request):
    users = Account.objects.all()
    return render(request,
                  "events/posts/feeds-additional_page.html",
                  {"users": users}
                  )


def add_event(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        location = request.POST.get('location')
        date = request.POST.get('date')
        time = request.POST.get('time')
        description = request.POST.get('description')
        user = User.objects.get(username=request.session.get('username'))
        new_event = Event(
            title=title,
            location=location,
            date=date,
            time=time,
            description=description,
            organizer=request.session.get('username'),
            user=user

        )
        new_event.save()
        # log the action
        action = Action(
            user=user,
            verb="created the new event",
            target=new_event
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully added a new event: %s" % new_event.title)
        return redirect('events:event_detail', new_event.id)
    else:
        return render(request, 'events/posts/add_new_event.html')


def edit_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    if request.method == 'POST':
        title = request.POST.get('title')
        if event.title != title:
            title_change_action = Action(
                user=event.user,
                verb="edited the event title",
                target=event
            )
            title_change_action.save()

        description = request.POST.get('description')
        if event.description != description:
            description_change_action = Action(
                user=event.user,
                verb="edited the event description",
                target=event
            )
            description_change_action.save()

        event.location = request.POST.get('location')
        event.date = request.POST.get('date')
        event.time = request.POST.get('time')
        event.title = title
        event.description = description
        event.save()
        messages.add_message(request, messages.INFO, "You successfully edit the event: %s" % event.title)
        return redirect('events:event_detail', event_id)
    else:
        return render(request,
                      "events/posts/add_new_event.html", {'event': event})


def event_button_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        event_id = request.POST.get('event_id')
        button_name = request.POST.get('button_name')
        try:
            event = Event.objects.get(pk=event_id)
            if button_name == 'shareButton':
                event.share_number = event.share_number + 1
            else:
                event.like_number = event.like_number + 1
            event.save()
            return JsonResponse(
                {'success': 'success', 'button_name': button_name, 'like_number': event.like_number,
                 'share_number': event.share_number},
                status=200)
        except Event.DoesNotExist:
            return JsonResponse({'error': 'No Event found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def delete_event(request):
    if request.method == 'POST':
        event_id = request.POST.get('event_id')
        event = Event.objects.get(pk=event_id)
        event.is_deleted = True
        event.save()
        delete_event_action = Action(
            user=event.user,
            verb="delete the event",
            target=event
        )
        delete_event_action.save()
        messages.add_message(request, messages.WARNING, "You successfully delete the event: %s" % event.title)
        redirect('events:events_list')
    return redirect('events:events_list')


def user_info_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        user_id = request.POST.get('user_id')
        print(user_id)
        try:
            user = Account.objects.get(pk=user_id)
            return JsonResponse(
                {'success': 'success', 'name': user.title, 'age': user.age,
                 'gender': user.gender, 'group': user.group, 'intro': user.intro},
                status=200)
        except Account.DoesNotExist:
            return JsonResponse({'error': 'No User profile found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)


def event_register_interaction(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        event_id = request.POST.get('event_id')
        button_text = request.POST.get('button_text')
        try:
            event = Event.objects.get(pk=event_id)
            if button_text == "Register":
                event.attendees += 1
                button_name = "Unregister"
            else:
                event.attendees -= 1
                button_name = "Register"
            event.save()
            return JsonResponse(
                {'success': 'success', 'attendees': event.attendees, 'button_name': button_name},
                status=200)
        except Event.DoesNotExist:
            return JsonResponse({'error': 'No Event found with that id.'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax Request'}, status=400)

templates/events/base.html
{% load static %}
<!doctype html>
<html lang="en">
<!--This page is the event page of the website-->
<head>
    <title>List item Page | {% block page-title %} {% endblock %}</title>
    <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, minimum-scale=1"
          name="viewport"/>
    <meta content="The list item page for GreatFalls Networking" name="description">
    <link href="{% static "css/app.css" %}" rel="stylesheet">
    <link href="{% static "css/app_header_without_login.css" %}" rel="stylesheet">
    <link href="{% static "css/app-footer.css" %}" rel="stylesheet">

</head>
<body>
<header>
    <div id="subHeader">
        <div id="leftHeader">
            <div id="logo">
                <a href="{% url "index" %}">
                    <img alt="GreatFalls Logo" height="150"
                         src="{% static "img/site/logo.png" %}" width="300"/>
                </a>
            </div>
        </div>
        <div id="midHeader">
            <a href="{% url "index" %}">
                GreatFalls Networking
            </a>
            <form action="{% url 'events:search_result' %}" method="get" class="searchForm">
                <input id="searchBar" name="search-topics" placeholder=" Any topic interested?"
                       type="text">

                <input alt="Search Icon" height="35"
                       id="searchIcon" name="submit" src="{% static "img/site/search-icon.png" %}"
                       type="image"
                       width="35"/>
            </form>
        </div>
        <div id="rightHeader">
            {% if request.session.username %}
                <form id="login-box">
                    <p>Logged in as <a href={% url 'users:profile' request.session.username %}>  <strong>{{ request.session.username }}</strong></a>|
                        <a href="{% url 'users:logout' %}"> Log out</a></p>
                </form>
            {% else %}
                <form id="login-box" action="{% url "users:login" %}" method="POST">
                    {% csrf_token %}
                    <input name="username" placeholder="Username" type="text">
                    <input name="pw" placeholder="Password" type="password">
                    <input name="submit" type="submit" value="Log in"> or <a
                        href="{% url 'users:register' %}">Register</a>
                </form>
            {% endif %}
        </div>
    </div>
    <ul id="menu">
        <li><a href="{% url "events:events_list" %}">Events</a></li>
        <li><a href="{% url "events:feed_page" %}">Feed</a></li>
        <li><a href="{% url "events:add_event" %}">Create Events</a></li>
        <li><a href="#covid19">Covid-19</a></li>
        <li><a href="#contact">Contact Us</a></li>
    </ul>
</header>
<main>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- main content of list item page-->
    {% block side-tabs %}{% endblock %}
    <!--event block area. There are three event blocks in the page-->
    {% block contentForList %}{% endblock %}
    <!--main content for item detail page-->
    {% block detailContent %}{% endblock %}
    {% block detailContentRecentPhotos %}{% endblock %}
    <!-- main content of other pages-->
    {% block content %}{% endblock %}

</main>

<footer>
    <div id="leftFooter">
        <p><b> Stay Connected </b></p>
        Keep up on newest special offers and events
        <div class="horizontal">
            <a href="#"><img alt="social media"
                             height="30"
                             src="{% static "img/site/social-media-icon.png" %}"
                             width="150"></a>
        </div>
    </div>
    <div id="midFooter">
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Directions</a></li>
            <li><a href="#">Blog</a></li>
        </ul>
    </div>
    <div id="rightFooter">
        <div class="flexItem">
            &copy; 2021 Great Falls Networking
        </div>
    </div>
</footer>
</body>

</html>